#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SantasToyFactory.MySqlConnector	
{
	public partial class ReportModel : OpenAccessContext, IReportModelUnitOfWork
	{
        private static string connectionStringName = @"connectionId";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = new ReportModelMetadataSource();
		
		public ReportModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public ReportModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public ReportModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public ReportModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public ReportModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
            backend.Backend = "MySql";
            backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}

        public IQueryable<ToyReport> ToyReports
        {
            get
            {
                return this.GetAll<ToyReport>();
            }
        }
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of ReportModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of ReportModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);

        public void UpdateSchema()
        {
            var handler = this.GetSchemaHandler();
            string script = null;
            try
            {
                script = handler.CreateUpdateDDLScript(null);
            }
            catch
            {
                bool throwException = false;
                try
                {
                    handler.CreateDatabase();
                    script = handler.CreateDDLScript();
                }
                catch
                {
                    throwException = true;
                }
                if (throwException)
                    throw;
            }
            if (string.IsNullOrEmpty(script) == false)
            {
                handler.ExecuteDDLScript(script);
            }
        }
		
	}
	
	public interface IReportModelUnitOfWork : IUnitOfWork
	{
	}
}
#pragma warning restore 1591
